name: Node.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - name: Installing dependecies
              run: npm install
            - name: Load svg to react dependecies
              run: node load-icons.js
            - uses: actions/checkout@v2
            - name: publish to npm
              run: npm install -g np && np publish --access public
            - uses: actions/checkout@v2
              with:
                  name: solomon-fibonacci/basicon-ui
                  ref: refs/heads/master
